defaults: &defaults
  working_directory: ~/antd-scss-theme-plugin
  docker:
    - image: circleci/node:8.11.3

whitelist: &whitelist
  paths:
    - __tests__/*
    - .babelrc
    - .eslintrc
    - .gitignore
    - jest.config.js
    - build/*
    - misc/*
    - LICENSE.md
    - package.json
    - README.md
    - src/*
    - yarn.lock

version: 2
jobs:
  checkout:
    <<: *defaults
    steps:
      - checkout
      - restore_cache:
          key: yarn-cache-{{ checksum "yarn.lock" }}
      - run:
          name: Install Dependencies
          command: yarn install
      - save_cache:
          key: yarn-cache-{{ checksum "yarn.lock" }}
          paths:
            - ./node_modules
      - persist_to_workspace:
          root: ~/antd-scss-theme-plugin
          paths:
          <<: *whitelist

  build:
    <<: *defaults
    steps:
      - attach_workspace:
          at: ~/antd-scss-theme-plugin
      - restore_cache:
          key: yarn-cache-{{ checksum "yarn.lock" }}
      - run:
          name: Build
          command: yarn build
      - store_artifacts:
          path: ./build/dist
          destination: dist
      - persist_to_workspace:
          root: ~/antd-scss-theme-plugin
          paths:
          <<: *whitelist

  test:
    <<: *defaults
    steps:
      - attach_workspace:
          at: ~/antd-scss-theme-plugin
      - restore_cache:
          key: yarn-cache-{{ checksum "yarn.lock" }}
      - run:
          name: Test
          command: yarn test

  deploy:
    <<: *defaults
    steps:
      - attach_workspace:
          at: ~/antd-scss-theme-plugin
      - run:
          name: Write NPM Token to ~/.npmrc
          command: echo "//registry.npmjs.org/:_authToken=$NPM_DEPLOY_TOKEN" >> ~/.npmrc
      - run:
          name: Install dot-json package
          command: npm install dot-json
      - run:
          name: Write version to package.json
          command: $(yarn bin)/dot-json package.json version ${CIRCLE_TAG:1}
      - run:
          name: Publish to NPM
          command: npm publish --access=public

workflows:
  version: 2

  build:
    jobs:
      - checkout
      - build:
          filters:
            tags:
              ignore: /v[0-9]+(\.[0-9]+)*/
          requires:
            - checkout
      - test:
          filters:
            tags:
              ignore: /v[0-9]+(\.[0-9]+)*/
          requires:
            - build

  release:
    jobs:
      - checkout:
          filters:
            tags:
              only: /v[0-9]+(\.[0-9]+)*/
            branches:
              ignore: /.*/
      - build:
          filters:
            tags:
              only: /v[0-9]+(\.[0-9]+)*/
            branches:
              ignore: /.*/
          requires:
            - checkout
      - test:
          filters:
            tags:
              only: /v[0-9]+(\.[0-9]+)*/
            branches:
              ignore: /.*/
          requires:
            - build
      - deploy:
          filters:
            tags:
              only: /v[0-9]+(\.[0-9]+)*/
            branches:
              ignore: /.*/
          requires:
            - test
